inherit_from:
  - .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-performance

AllCops:
  NewCops: enable
  Exclude:
    - 'Guardfile'
    - 'Rakefile'
    - 'bin/**/*'
    - 'config/**/*'
    - 'spec/fixtures/**/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'
  TargetRubyVersion: 2.7

Rails:
  Enabled: true

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Layout/LineLength:
  Max: 120
  Exclude:
    - 'spec/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/ParameterLists:
  Max: 6
  Exclude:
    - 'spec/rails_helper.rb'

Rails/OutputSafety:
  Exclude:
    - 'app/helpers/embed_helper.rb'
